#server:
#  port: 8106
##  
##eureka:
##  client:
##    registerWithEureka: true
##    fetchRegistry: true
#  
##eureka:
##  client:
##    serviceUrl:
##      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
##    registry-fetch-interval-seconds: 60
##    
#spring:
#            
#  datasource:
#    url: jdbc:mysql://localhost:3306/sardb
#    username: bybdbuser
#    password: saudara123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      ddl-auto: validate